### ISSUE TITLE
NameError: name 'today' is not defined

### ISSUE THREAD

**Issue by Rheffner02** [faulander/720dl#1]
Hello. I have installed and setup a VENV in pdm I have installed the initial dependencies of pyyaml, flask, selenium, loguru, and pendulum I am attempting to run 720pdl.py, but get the following error and no yaml file is generated:
`Traceback (most recent call last):
  File "C:\Users\<USER>\Desktop\Python 720\720dl-master\720pdl.py", line 257, in <module>
    cfg = loadOrCreateCfgfile()
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<USER>\Desktop\Python 720\720dl-master\720pdl.py", line 32, in loadOrCreateCfgfile
    c['Default']['skipOlderThan'] = today.start_of("year").format("YYYY-MM-DD")
                                    ^^^^^
NameError: name 'today' is not defined`

I would really appreciate any help on getting passed this  error as I have spent a lot of time trying to get the dependencies in place to run this. 

Thanks for any help! LINE 32

![Screenshot 2023-11-27 041242](https://github.com/faulander/720dl/assets/127645210/975d7026-2952-466a-a135-2a8a447a69f0)

**Comment by godver3** [comment]
The quick fix is to add a quick definition in the .py file at the start of loadOrCreateCfgfile():

```
def loadOrCreateCfgfile():
    today = pendulum.now()  # Define today using Pendulum
    # ... rest of the function ...
```

I've created a pull request.
